#!/usr/bin/env php
<?php
$baseDir = __DIR__;
require_once __DIR__.'/../../../autoload.php';


/*
 * Using "kh411d/laravel-odm" package
 *
 */
    $app = require_once __DIR__.'/../../../../bootstrap/start.php';
    $app->boot();
    $dm = $app['odm.documentmanager'];

/**/


/* Define STDIN in case if it is not already defined by PHP for some reason */
    if(!defined("STDIN")) {
        define("STDIN", fopen('php://stdin','r'));
    }

    echo "Database Name (enter below):\n";
    $db = fread(STDIN, 80); // Read up to 80 characters or a newline


    $app['config']->set('laravel-odm::connection.options.db',trim($db));
    $dm = $app['odm.documentmanager'];

/**/






/*
 * Copy paste from http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/console-commands.html
 * Pass Document Manager to Symfony CLI Console 
 */

    $helpers = array('dm' => new Doctrine\ODM\MongoDB\Tools\Console\Helper\DocumentManagerHelper($dm));
    $helperSet = isset($helperSet) ? $helperSet : new \Symfony\Component\Console\Helper\HelperSet();
    foreach ($helpers as $name => $helper) { $helperSet->set($helper, $name); }

    $cli = new \Symfony\Component\Console\Application('Doctrine ODM MongoDB Command Line Interface', null);
    $cli->setCatchExceptions(true);
    $cli->setHelperSet($helperSet);
    $cli->addCommands(array(
        new \Doctrine\ODM\MongoDB\Tools\Console\Command\QueryCommand(),
        new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateDocumentsCommand(),
        new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateRepositoriesCommand(),
        new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateProxiesCommand(),
        new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateHydratorsCommand(),
        new \Doctrine\ODM\MongoDB\Tools\Console\Command\ClearCache\MetadataCommand(),
        new \Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\CreateCommand(),
        new \Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\DropCommand(),
    ));
    $cli->run();