#!/usr/bin/env php
<?php
$baseDir = __DIR__;
require $baseDir.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/start.php';

$app->boot();
$dm = $app['odm.documentmanager'];

/*
 * If not Using LaravelOdm ( $app['odm.documentmanager'] ) please uncomment this.
 * Configuration, please do config manually
 *
    use Doctrine\Common\Annotations\AnnotationReader;
    use Doctrine\ODM\MongoDB\DocumentManager;
    use Doctrine\MongoDB\Connection;
    use Doctrine\ODM\MongoDB\Configuration;
    use Doctrine\ODM\MongoDB\Mapping\Driver\AnnotationDriver;

    $conf = array(
                    'conn' => array(
                                     'server' => null,
                                     'options' => array( 'username' => null,
                                                         'password' => null,
                                                         'db'       => 'ccrm')
                    ),
                    'dir' => array(
                            'proxy'    => $baseDir.'/app/storage/cache',
                            'hydrator' => $baseDir.'/app/storage/cache',
                            'document' => $baseDir.'/app/models'
                    ),
    );

    $config = new Configuration();
    $config->setProxyDir($conf['dir']['proxy']);
    $config->setProxyNamespace('Proxies');
    $config->setHydratorDir($conf['dir']['hydrator']);
    $config->setHydratorNamespace('Hydrators');
    AnnotationDriver::registerAnnotationClasses();
    $reader = new AnnotationReader();
    $config->setMetadataDriverImpl(new AnnotationDriver($reader, $conf['dir']['document']));
    $config->setDefaultDB($conf['conn']['options']['db']);

    $dm = DocumentManager::create(new Connection($conf['conn']['server'],$conf['conn']['options']), $config);
/**/





/*
 * Copy paste from http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/console-commands.html
 * Pass Document Manager to Symfony CLI Console 
 */

    $helpers = array('dm' => new Doctrine\ODM\MongoDB\Tools\Console\Helper\DocumentManagerHelper($dm));
    $helperSet = isset($helperSet) ? $helperSet : new \Symfony\Component\Console\Helper\HelperSet();
    foreach ($helpers as $name => $helper) { $helperSet->set($helper, $name); }

    $cli = new \Symfony\Component\Console\Application('Doctrine ODM MongoDB Command Line Interface', Doctrine\ODM\MongoDB\Version::VERSION);
    $cli->setCatchExceptions(true);
    $cli->setHelperSet($helperSet);
    $cli->addCommands(array(
        new \Doctrine\ODM\MongoDB\Tools\Console\Command\QueryCommand(),
        new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateDocumentsCommand(),
        new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateRepositoriesCommand(),
        new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateProxiesCommand(),
        new \Doctrine\ODM\MongoDB\Tools\Console\Command\GenerateHydratorsCommand(),
        new \Doctrine\ODM\MongoDB\Tools\Console\Command\ClearCache\MetadataCommand(),
        new \Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\CreateCommand(),
        new \Doctrine\ODM\MongoDB\Tools\Console\Command\Schema\DropCommand(),
    ));
    $cli->run();